---
name: Realify
description: A new Flutter project.
publish_to: none
version: 1.0.1+2
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  cached_network_image: ^3.0.0
  calendar_strip: ^1.0.6
  change_app_package_name: ^1.0.0
  cloud_firestore: ^2.2.2
  community_material_icon: ^5.4.55
  cupertino_icons: ^1.0.0
  custom_dialog: ^0.0.2
  custom_dialog_box: ^0.0.1
  dotted_border: ^1.0.6
  draggable_scrollbar_sliver: ^0.0.3
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  firebase_storage: ^8.1.3
  flutter_bloc: ^7.0.1
  flutter_icons: ^1.1.0
  flutter_launcher_icons: ^0.9.0
  flutter_statusbarcolor: ^0.2.3
  flutter_vector_icons: ^0.2.1
  fluttericon: ^1.0.7
  form_field_validator: ^1.1.0
  google_maps_flutter: ^2.0.6
  google_sign_in: ^5.0.4
  hexcolor: ^1.0.6
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  line_awesome_flutter: ^1.0.1
  multi_image_picker2: ^5.0.2
  octicons_icon: ^0.0.2
  outline_material_icons: ^0.1.1
  package_info_plus: ^1.0.3
  path: ^1.8.0
  path_provider: ^2.0.2
  readmore: ^2.0.0
  shimmer: ^2.0.0
  sms_autofill: ^2.0.0
  url_launcher: ^6.0.7
  uuid: ^3.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  hive_generator: ^1.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/icons/
    - assets/json/
    - assets/json/favourite.json
    - assets/json/floor.json
    - assets/json/location.json
    - assets/json/properties.json
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: JosefinSans-Regular
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
    - family: JosefinSans-semiBold
      fonts:
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
    - family: Mackless-Script
      fonts:
        - asset: assets/fonts/Mackless-Script.otf
